### ISSUE TITLE
extending/optimizing annotation objects

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_SANDS#137]
Currently the AtlasAnnotation and CustomAnnotation schema are very similar:
| properties | AtlasAnnotation | CustomAnnotation |
| --- | --- | --- |
| **bestViewPoint**: linking to a CoordinatePoint instance | Y | Y |
| **coordinateSpace**: linking to a CommonCoordinateSpace OR a CustomCoordinateSpace | **N** | Y |
| **criteria**: linking to a ProtocolExecution instance | Y | Y |
| **criteriaQualityType**: linking to a CriteriaQualityType | Y | Y |
| **displayColor**: stating a display color as string (format: HEX) | Y | Y |
| **inspiredBy**: linking to all File instances (used to generate the annotation) | Y | Y |
| **internalIdentifier**: string (ID used for annotation within visualizedIn File) | Y | Y |
| **laterality**: linking to Laterality instance | Y | Y |
| **lookupLabel**:  stating a lookup label as string | Y | Y |
| **visualizedIn**: linking to the File instance in which this annotation is visualized | Y | Y |

The reason why the AtlasAnnotation does not have a link to a CommonCoordinateSpace lies in the fact that an AtlasAnnotation can only exist as an instance of a BrainAtlasVersion (via ParcellationTerminologyVersion and ParcellationEntityVersion) which has a dedicated CommonCoordinateSpace already assigned.

Nonetheless I think there are some parts missing to allow full functionalities of how annotations are typically used (as done for example in siibra).

1. We could introduc a concept Annotation schema that both annotation inherit from to reduce maintenance issues.
2. I think we need to extend the linked types of the **visualizedIn** properties, in particular for CustomAnnotations. Annotations can be larger volume of interests or 2D delineations stored in Files (current assumptions), but they could also be relatively small things such as landmarks (coordinate points), smaller 2D delineations (polygons) etc. that can immediately stored as SANDS instances.
2. Bothe annotations should get a type (suggestions: landmark, delineation (2D polygons), volume of interest (3D) + ???).
3. We should discuss if **inspiredBy** could also link to another annotation (e.g., the probability map annotations of Julich-Brain Atlas are the base for the maximum probability map annotations of the Julich-Brain Atlas).
4. We should introduce maybe a **definition** property (optional) for annotations (at least for CustomAnnotation).

@UlrikeS91 @dickscheid @xgui3783 @skoehnen @tgbugs @aeidi89 what do you think? Anything else that you'd like to discuss around AtlasAnnotations and CustomAnnotations?

**Comment by UlrikeS91** [comment]
My thoughts to your points: 

> 1. We could introduc a concept Annotation schema that both annotation inherit from to reduce maintenance issues.

Yes, very good idea. Totally support this!


> 2. I think we need to extend the linked types of the **visualizedIn** properties, in particular for CustomAnnotations. Annotations can be larger volume of interests or 2D delineations stored in Files (current assumptions), but they could also be relatively small things such as landmarks (coordinate points), smaller 2D delineations (polygons) etc. that can immediately stored as SANDS instances.

We talked about this before. I agree, but also see point 3. 


> 3. Bothe annotations should get a type (suggestions: landmark, delineation (2D polygons), volume of interest (3D) + ???).

Looking at this point on its own, yes, good idea. But if we combine this with point 2, wouldn't this be redundant or at least introduce a source for errors? I know that `visualizedIn` is an optional property and a `type` field would generally be very useful, but it can introduce errors (e.g. mismatch between what is linked under `visualizedIn` and what type has been stated). 

There is also the issue of ambiguity. Talking about landmarks/coordinate points (the plural of it), it sounds like we would need to expand the count to 0 - N; and then for both `type` and `visualizedIn`. If both have more than one value, which ones belong to which?    


> 4. We should discuss if **inspiredBy** could also link to another annotation (e.g., the probability map annotations of Julich-Brain Atlas are the base for the maximum probability map annotations of the Julich-Brain Atlas).

I don't see why not and it is a valid use case. We should maybe consider how `protocolExecutions` come in here, though. For this specific use case, one could argue that a `protocolExecution` would create the link between PM annotations (their `visualizedIn` files being also the input for the PrEx) and MPM annotations (their `visualizedIn` files being also output for the PrEx).

Eitherway, if we want to create rather direct links between annotations, `inspiredBy` may not be the property for it. I'm thinking more about the semantics here. I understand `inspiredBy` rather literally, as in "This annotation has been inspired by those files. We may have looked at those files and got some ideas about how to create the annotation because of it but we cannot say to which extend the annotation was created as a result of it". 
We do have a property that would give a more direct link: `descendedFrom`. Maybe worth introducing this in addition or even instead of `inspiredBy`?   


> 5. We should introduce maybe a **definition** property (optional) for annotations (at least for CustomAnnotation).

Not sure what you mean here. Can you elaborate a bit more on this?

**Comment by aeidi89** [comment]
Here is my response:

> 1. We could introduc a concept Annotation schema that both annotation inherit from to reduce maintenance issues.

How would this work in relation to coordinateSpace, would that be removed from conceptAnnotation as it is not similar in the two others?

> 2. I think we need to extend the linked types of the **visualizedIn** properties, in particular for CustomAnnotations. Annotations can be larger volume of interests or 2D delineations stored in Files (current assumptions), but they could also be relatively small things such as landmarks (coordinate points), smaller 2D delineations (polygons) etc. that can immediately stored as SANDS instances.

On the go, this sound reasonable to me, however, it sound like @UlrikeS91 has a point about the redundancy regarding question 3.

> 3. Bothe annotations should get a type (suggestions: landmark, delineation (2D polygons), volume of interest (3D) + ???).

> 4. We should discuss if **inspiredBy** could also link to another annotation (e.g., the probability map annotations of Julich-Brain Atlas are the base for the maximum probability map annotations of the Julich-Brain Atlas).

In relations to probability maps this sounds reasonable. If there are an other similar example, that would also be interesting to compare.

> 5. We should introduce maybe a **definition** property (optional) for annotations (at least for CustomAnnotation).

Do you mean definition/description, as in the annotator can define/describe why the annotation was made, or what it is?

**Comment by lzehl** [comment]
@aeidi89 point 1: the extended schemas would look exactly as they look now (AtlasAnnotation would not state a CoordinateSpace since this is defined for the whole BrainAtlasVersion already).

@UlrikeS91 & @aeidi89 point 2 / 3: it is not redundant when pointing to a File in which the annotation is contained. Here I do not know what type the annotation actually is. Considering mismatches: we cannot use this anymore as an argument... we have these issues for a number of different points in the model, which we just need to flag for curation (now) and a future graph validation for openMINDS. I think we could rename "visualizedIn" with "definedIn" and then either point to the File (if it is stored/defined in there) or the new schemas (if it is stored/defined in there).

@UlrikeS91 point 4: I see it currently that way: a File is potentially ambiguous in this context. I might not have been inspired by the whole file, but a specific part of it. As for ProtocolExecutions: I already suggested this to Xiao: I think in the long run we should define specific activity schemas for SANDS (and treat this as an in-depth extension for atlases and spatial registration/transformation) and not use protocol executions. In principle the "inspiredBy" is a shortcut if the "criteria" is not defined. But this point needs more discussion time.

@aeidi89 point 4: I currently did not discover another use case for this but I keep my eyes open.
 
@aeidi89  point 5: yes. I think this would be helpful (as option) in particular for the custom annotations

**Comment by lzehl** [comment]
I will close this issue since it is now discussed in #183
