### ISSUE TITLE
[feature request] refactoring atlas.parcellationEntityVersion.hasAnnotation

### ISSUE THREAD

**Issue by xgui3783** [openMetadataInitiative/openMINDS_SANDS#174]
Per discussion with @lzehl (please edit directly/comment if inaccuracy / anything missing )

There appears to be many types of annotations (deterministic vs probabilistic vs surface projection). the current `atlasAnnotation` schema does not seem to cover the needs of each:

- `displayColor` makes little sense for probabilistic annotations
- `bestViewPoint` makes little sense for surface projection
- it would be ideal to have `min` / `max` for probabilistic annotations

Ideally, we would have different specialized types of annotations.

**Comment by xgui3783** [comment]
Not discussed in the meeting, but it just occurred to me that another way to approach this might be

`AtlasAnnotation` as the base schema

`ProbabilisticAtlasAnnotation` extends `AtlasAnnotation`, with
- `min` / `max`
- `bestViewPoint`

`DeterministicAtlasAnnotation` extends `AtlasAnnotation`, with
- `displayColor`
- `bestViewPoint`

etc

**Comment by lzehl** [comment]
as alternative, since all of these are anyway optional properties I was thinking of extracting those into a separate schema or schemas.

Let's collect what we would like to have:

**centroid** 
+ instead of "best view point"
+ could be kept in annotation

**displayColor** 
+ does not have to be one value
+ should maybe link to a schema (colorization) or schemas (Color, Colormap)

**bestView**
+ with camera angle, best view point (if other than centroid), camera distance

@xgui3783 what else?

**Comment by xgui3783** [comment]
Sounds good!

Although, I would there still be a formal way to record label index (in the case of deterministic/surface projection (?); min/max for probabilistic annotation.

This would be very much describing the data.

Perhaps a `annotationAttributes` property, with a list (0-n) of embedded items. Each item is any one of `range` (probably does not exist yet) or `value`.

Would love your feedback @lzehl

**Comment by lzehl** [comment]
@xgui3783 we need to make this more concrete. What attributes (key-value pairs; value can be also an array) would you like to have for what purpose? Could you make a list?

**Comment by lzehl** [comment]
should be merged into the discussion here #183
