### ISSUE TITLE
consistency change? split CCS into CCS and CCSV

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_SANDS#210]
For consistency reasons I'm getting the feeling we should treat the Common Coordinate Space as a "special" Research Product split into:
- Common Coordinate Space (version independent research product representation)
- Common Coordinate Space Version (version dependent research product representation

I know we had that discussion once already but I would like to bring it up again.
@UlrikeS91 @tgbugs @skoehnen @ehennestad @apdavison what do you think?

**Comment by tgbugs** [comment]
That is consistent with what AtOM says we should do and I think it bears out for things like WHSSD where 1.0 -> 1.01 was the result of a tweak to the coordinate space.

The one subtle point would be, as with all the other version specific variants, that it should only be changed if it actually changes and otherwise remain the same between versions so long as it did not change.
